"use strict";
const $=id=>document.getElementById(id);
let mode="proxy",booted=false,ruleMode=null,pollTimer=0,pollTicket=0,resultKind="live-results",resultPage=1,candidatePage=1,competitionPage=1,cloudPage=1;
let timing={elapsed_seconds:0,software_seconds:0,active:false},timingAnchor=performance.now(),lastLog="";
const signatures=new Map(),modes={proxy:"代理三网站测速",tcp_tls:"免代理 TCP／TLS 测速"};
const proxyFields=[
 ["publish_count","常规 IP 发布数量",1,1000,1],["jp_publish_count","日本追加发布数量",0,300,1],
 ["batch_size","每批节点数",1,100,1],["round_count","每站连接次数",5,10,1],
 ["max_entry_latency_ms","入口延迟上限（毫秒）",1,10000,1],["max_proxy_average_latency_ms","三网平均延迟上限（毫秒）",1,10000,1],
 ["max_proxy_loss_percent","最大请求失败率（%）",0,100,.1],["max_proxy_jitter_ms","最大响应抖动（毫秒）",0,10000,1],
 ["min_proxy_speed_mbps","最低下载速度（Mbps）",.01,100000,.01],["entry_timeout_seconds","入口连接超时（秒）",.1,5,.1],
 ["entry_concurrency","入口初筛并发上限",1,512,1],["delay_concurrency","网站测试并发上限",1,100,1],
 ["adaptive_concurrency","自动降低拥塞并发",0,1,1],["quick_finish","达到目标后提前竞赛",0,1,1],
 ["download_attempts","下载测速次数",1,10,1],["download_bytes","测速样本（MiB）",.5,8,.5],
 ["minimum_completion_ratio","最低正文完整度（%）",95,100,.1],["maximum_download_seconds","正文计时上限（秒）",.1,120,.1],
 ["request_timeout_seconds","网站请求超时（秒）",.1,60,.1],["download_timeout_seconds","下载 I/O 超时（秒）",.1,120,.1],
 ["speed_concurrency","下载并发上限",1,8,1],["round_cooldown_seconds","轮间隔（秒）",0,2,.1]
];
const tcpFields=[
 ["publish_count","常规 IP 发布数量",1,1000,1],["jp_publish_count","日本追加发布数量",0,300,1],
 ["max_tcp_average_latency_ms","TCP 三次平均延迟上限（毫秒）",1,10000,1],["max_loss_percent","最大 TCP／TLS 丢包率（%）",0,100,.1],
 ["max_jitter_ms","最大 TCP／TLS 抖动（毫秒）",0,10000,1],["min_download_mbps","最低下载速度（Mbps）",.01,100000,.01],
 ["tls_enabled","启用 TLS 三次握手验证",0,1,1],["max_tls_average_latency_ms","TLS 三次平均延迟上限（毫秒）",1,10000,1],
 ["tcp_attempts","每个 IP 的 TCP 连测次数",3,3,1],["tls_attempts","每个 IP 的 TLS 连测次数",3,3,1],
 ["tcp_timeout_seconds","每次 TCP 连接超时（秒）",.1,5,.1],["tls_timeout_seconds","每次 TLS／位置请求超时（秒）",.1,15,.1],
 ["tcp_concurrency","TCP 初筛并发上限",1,512,1],["tls_concurrency","TLS 检测并发上限",1,128,1],
 ["batch_size","后续测试每批节点数",1,100,1],["speed_concurrency","下载并发上限",1,8,1],
 ["download_bytes","测速样本（MiB）",.5,8,.5],["minimum_completion_ratio","最低正文完整度（%）",95,100,.1],
 ["maximum_download_seconds","正文计时上限（秒）",.1,120,.1],["download_timeout_seconds","下载 I/O 超时（秒）",.1,120,.1],
 ["quick_finish","达到目标后提前竞赛",0,1,1]
];
const helps={
 publish_count:"最终按本方式的实测排名取前多少个常规 IP，可填 100、200、300 等。发布前会与上一次本方式的名单重新竞赛。",
 jp_publish_count:"另外追加多少个日本 IP，不占常规名额，也不能重复。日本仍须通过同样的测速规则；设为 0 不要求日本名额。",
 batch_size:"后续独立节点的批次大小，最多 100。入口初筛会并行扫描完整候选池。",
 round_count:"每个网站至少测 5 次。每站去掉一次最高和一次最低，平均其余样本，再平均三个网站的结果；失败率仍统计全部请求。",
 max_entry_latency_ms:"本机连接候选 IP 端口的延迟上限，超过就淘汰。例如设置 200，240 毫秒不能通过。",
 max_proxy_average_latency_ms:"通过候选代理访问谷歌、Cloudflare 和 GitHub 的平均响应上限。按每站剔除最高最低后的均值合并判断。",
 max_proxy_loss_percent:"三个网站全部请求中允许失败的比例。设为 0 必须全部成功，不会因延迟剔除而忽略失败。",
 max_proxy_jitter_ms:"各轮三站响应平均值的标准差上限。数值越大表示波动越明显，超过就淘汰。",
 min_proxy_speed_mbps:"通过指定候选代理下载小样本的最低速度。低于该值淘汰；8 Mbps 约等于 1 MB/秒。",
 entry_timeout_seconds:"等待入口连接建立的最长时间，超时失败；与入口延迟上限分别判断。",
 entry_concurrency:"同时检查入口连接的最大数量。数值过高会增加本机连接压力，最多 512。",
 delay_concurrency:"同时测试网站响应的最大数量。启用拥塞控制时会在此上限以内自动降低并发。",
 adaptive_concurrency:"请求失败较多时降低并发，减轻网络拥塞；不会改变任何合格阈值或把失败算成成功。",
 quick_finish:"候选达到所设数量并留出复测余量后，提前进入竞赛。关闭时测完本轮所有候选；未测候选保留，可继续优选。",
 download_attempts:"每个代理重复下载测速的次数，各次都须成功，然后比较平均下载速度。",
 download_bytes:"每次下载的数据量，沿用原包的小样本方法。可选 0.5、1、2、4、8 MiB。",
 minimum_completion_ratio:"下载正文至少完成的比例，最低 95%。不足就拒绝，超时仍按失败处理。",
 maximum_download_seconds:"收到响应头后，传输正文的最长计时时间，超过就淘汰。",
 request_timeout_seconds:"每次网站访问和出口查询的最长等待时间，超时按请求失败处理。",
 download_timeout_seconds:"下载连接与响应的 I/O 等待时限，超时视为下载失败。",
 speed_concurrency:"同时下载的最大候选数量，最多 8。并发会共享本机带宽，过高可能降低单个 IP 的速度。",
 round_cooldown_seconds:"两轮网站访问之间的等待时间，设为 0 连续测试。",
 max_tcp_average_latency_ms:"每个 IP 连续建立 3 次 TCP 连接，取成功连接的算术平均；失败次数另外计入丢包率。平均值超过上限就淘汰。",
 max_loss_percent:"TCP 三次连接或 TLS 三次握手中的失败比例。每个阶段独立判断；三次中失败一次约为 33.33%。",
 max_jitter_ms:"TCP 或 TLS 三次成功测量值的标准差上限。超过就淘汰，抖动不是允许的平均延迟。",
 min_download_mbps:"直接连接候选 IP、下载原包小样本的最低速度。低于此值淘汰，不调用代理内核。",
 tls_enabled:"开启后，每个通过 TCP 初筛的 IP 再做 3 次 TLS 握手，验证证书并按 TLS 延迟、丢包和抖动筛选。下载仍使用 HTTPS。",
 max_tls_average_latency_ms:"三次 TLS 握手成功值的平均上限，包含连接与握手时间，超过就淘汰。",
 tcp_attempts:"沿用原包，每个 IP 连续测满 3 次 TCP，完整记录延迟与失败次数。",
 tls_attempts:"启用 TLS 时，每个 IP 连续测满 3 次握手，不用代理。",
 tcp_timeout_seconds:"单次 TCP 连接的最长等待时间，超时记为一次失败。",
 tls_timeout_seconds:"每次 TLS 握手或位置验证的最长等待时间，超时记为失败。",
 tcp_concurrency:"免代理初筛同时探测的最大 IP 数量。每个 IP 的三次测量仍连续进行，最多 512。",
 tls_concurrency:"同时执行 TLS 和后续检测的 IP 数量，最多 128；下载另受下载并发限制。"
};
const statuses={Queued:"未测试",Ready:"准备就绪",Running:"运行中",Paused:"已暂停",Stopped:"已停止并保存",Failed:"运行失败",Preparing:"准备任务",Dispatching:"请求云端",Downloading:"下载候选",Local:"本地实测",Publishing:"正在推送",Completed:"已完成",Qualified:"通过",completed:"完成",needs_more:"等待补测","Needs More":"等待补测","Loading Proxy":"加载独立节点","Speed Testing":"代理下载测速","Rejected Entry":"入口失败或超限","Rejected Loss":"网站请求失败率超限","Rejected Latency":"平均延迟超限","Rejected Speed":"下载速度不合格","Rejected Jitter":"抖动超限","Retest Required":"等待新规则复测","TCP Testing":"TCP 连接检测","TCP Passed":"TCP通过，等待后续检测","TLS Testing":"TLS三次握手","Direct Speed Testing":"直连下载测速","Direct Location":"核验位置","Rejected TCP":"TCP延迟／丢包／抖动不合格","Rejected TLS":"TLS握手／延迟／抖动不合格"};
const countryNames={JP:"日本",DE:"德国",US:"美国",HK:"中国香港",SG:"新加坡",KR:"韩国",NL:"荷兰",FR:"法国",GB:"英国",CN:"中国",TW:"中国台湾",AU:"澳大利亚",CA:"加拿大",SE:"瑞典",CH:"瑞士",AT:"奥地利",CZ:"捷克",PL:"波兰",RU:"俄罗斯",XX:"未知位置"};
const number=v=>v==null?"—":Number(v).toFixed(2),countryLabel=r=>countryNames[r.geo_country||r.country]||(r.geo_country||r.country||"未知位置");
const duration=s=>{const n=Math.max(0,Math.floor(s));return [Math.floor(n/3600),Math.floor(n/60)%60,n%60].map(v=>String(v).padStart(2,"0")).join(":");};
function label(value){if(statuses[value])return statuses[value];const m=/^Round (\d+)(?:: (\w+))?$/.exec(value||"");if(m)return `第 ${m[1]} 轮${m[2]?`：${({google:"谷歌",cloudflare:"Cloudflare",github:"GitHub"})[m[2]]||"网站"}`:""}`;return value&&/[\u4e00-\u9fff]/.test(value)?value:"等待更新";}
function feedback(text){$("feedback").textContent=text;}
async function post(action,payload={}){const r=await fetch(`/api/proxybench/${action}`,{method:"POST",headers:{"Content-Type":"application/json","X-ProxyBench":"1"},body:JSON.stringify({measurement_mode:mode,...payload})});const v=await r.json();if(!r.ok)throw Error(v.error||"操作未完成");return v;}
function renderTimer(){const delta=(performance.now()-timingAnchor)/1000;$("runTimer").textContent=duration(timing.elapsed_seconds+(timing.active?delta:0));$("timerDetail").textContent=`软件已打开 ${duration(timing.software_seconds+delta)}；${timing.active?"优选计时中":"优选计时已暂停或停止"}`;}
setInterval(renderTimer,1000);
function measurements(r){const direct=(r.measurement_mode||mode)==="tcp_tls";return {direct,response:direct?r.tcp_average_latency_ms:r.proxy_average_latency_ms??r.live_response_ms,loss:direct?r.tcp_loss_percent:r.proxy_loss_percent,jitter:direct?r.tcp_jitter_ms:r.latency_jitter_ms,speed:direct?r.download_mbps:r.proxy_download_average_mbps};}
async function copyIP(row){try{await navigator.clipboard.writeText(row.ip);feedback(`已复制 IP：${row.ip}`);}catch{feedback("浏览器暂时不能复制，可选中 IP 地址手动复制。");}}
function cell(tr,text){const td=document.createElement("td");td.textContent=text;tr.append(td);return td;}
function operations(tr,row){const td=document.createElement("td");for(const [title,handler] of [["复制",()=>copyIP(row)],["详情",()=>detail(row)]]){const button=document.createElement("button");button.className="button secondary row-button";button.textContent=title;button.setAttribute("aria-label",`${title} ${row.ip}`);button.addEventListener("click",handler);td.append(button);}tr.append(td);}
function renderResults(id,rows){const signature=mode+JSON.stringify(rows);if(signatures.get(id)===signature)return;signatures.set(id,signature);const body=$(id),fragment=document.createDocumentFragment();for(const row of rows){const tr=document.createElement("tr"),m=measurements(row);for(const value of [`${row.ip}:${row.port}`,countryLabel(row),number(m.response),m.loss==null?"—":`${number(m.loss)}%`,number(m.jitter),number(m.speed),label(row.status||(row.qualified?"Qualified":"Queued"))])cell(tr,value);tr.classList.toggle("qualified-row",!!row.qualified);tr.classList.toggle("rejected-row",String(row.status).startsWith("Rejected"));operations(tr,row);fragment.append(tr);}if(!rows.length){const tr=document.createElement("tr"),td=cell(tr,id==="competitionBody"?"发布前竞赛开始后，复测结果会实时显示在这里。":"开始测试后，测量和自动淘汰结果会实时显示在这里。");td.colSpan=8;td.className="empty-list";fragment.append(tr);}body.replaceChildren(fragment);}
function pager(type,value){const map={result:["resultPageInfo","resultPrevious","resultNext","resultPageNumber"],competition:["competitionPageInfo","competitionPrevious","competitionNext"],cloud:["cloudPageInfo","cloudPrevious","cloudNext"],candidate:["pageInfo","previousPage","nextPage","pageNumber"]};const [info,previous,next,input]=map[type];$(info).textContent=`第 ${value.page} / ${value.pages} 页`;$ (previous).disabled=value.page<=1;$(next).disabled=value.page>=value.pages;if(input){$(input).max=value.pages;if(document.activeElement!==$(input))$(input).value=value.page;}}
async function refreshResults(){const expected=mode,kind=resultKind,v=await post(kind,{page:resultPage});if(mode!==expected||kind!==resultKind)return;resultPage=v.page;renderResults("resultBody",v.rows);$("resultTotal").textContent=`${v.total.toLocaleString("zh-CN")} 个 IP，每页 300`;pager("result",v);}
async function refreshCompetition(){const expected=mode,v=await post("competition-results",{page:competitionPage});if(mode!==expected)return;competitionPage=v.page;renderResults("competitionBody",v.rows);$("competitionTotal").textContent=`${v.total.toLocaleString("zh-CN")} 个 IP`;pager("competition",v);}
async function refreshCandidates(){const expected=mode,v=await post("candidates",{page:candidatePage});if(mode!==expected)return;candidatePage=v.page;const fragment=document.createDocumentFragment();for(const row of v.rows){const tr=document.createElement("tr");for(const text of [`${row.ip}:${row.port}`,(row.source_names||[]).map(name=>({"fixed-source-a":"链接一","fixed-source-b":"链接二","cloudflare-official":"边缘池","gslege-jp-hint":"日本补充"}[name]||"补充来源")).join("、"),number(row.entry_latency_ms),label(row.status)])cell(tr,text);fragment.append(tr);}$("tbody").replaceChildren(fragment);$("listTotal").textContent=`${v.total.toLocaleString("zh-CN")} 个 IP，每页 300`;pager("candidate",v);}
async function refreshCloud(){const v=await post("cloud-published-results",{page:cloudPage});cloudPage=v.page||1;const fragment=document.createDocumentFragment();for(const row of v.rows){const tr=document.createElement("tr"),m=measurements(row);for(const text of [row.rank,`${row.ip}:${row.port}`,countryLabel(row),m.direct?"TCP／TLS":"代理三网",`${number(m.response)}${m.direct?"（TCP）":"（访问指定网站）"}`,m.loss==null?"—":`${number(m.loss)}%`,number(m.jitter),number(m.speed),row.lane==="jp_append"?"日本追加":"常规"])cell(tr,text);operations(tr,row);fragment.append(tr);}if(!v.rows.length){const tr=document.createElement("tr"),td=cell(tr,"暂无已确认的云端名单。完成优选或手动推送后显示实际结果。");td.colSpan=10;td.className="empty-list";fragment.append(tr);}$("cloudPublishedBody").replaceChildren(fragment);pager("cloud",{...v,pages:v.pages||1,page:v.page||1});}
function detail(row){const m=measurements(row);$("detailTitle").textContent=`${row.ip}:${row.port} 的实测数据`;const box=$("detailBody");box.replaceChildren();const heading=document.createElement("p");heading.textContent=`${m.direct?"免代理 TCP／TLS":"代理三网站"}；${countryLabel(row)}；${label(row.status||(row.qualified?"Qualified":"Queued"))}`;box.append(heading);const table=document.createElement("table"),header=document.createElement("tr");for(const text of ["测量项目","原始测量（毫秒）","平均值"])cell(header,text);table.append(header);const sites=m.direct?[["tcp","TCP 连续三次"],["tls","TLS 连续三次"]]:[["google","谷歌"],["cloudflare","Cloudflare"],["github","GitHub"]];for(const [key,title] of sites){const tr=document.createElement("tr"),values=row[`${key}_rounds_ms`]||(row.probes?.[key]||[]).map(p=>p.latency_ms);cell(tr,title);cell(tr,values.length?values.map((v,i)=>`第${i+1}次 ${v==null?"失败":number(v)}`).join("；"):"未测或未启用");cell(tr,number(row[`${key}_average_latency_ms`]??row[`${key}_average_ms`]));table.append(tr);}box.append(table);const summary=document.createElement("p");summary.textContent=`最终延迟 ${number(m.response)} 毫秒；丢包／失败率 ${number(m.loss)}%；抖动 ${number(m.jitter)} 毫秒；下载 ${number(m.speed)} Mbps。${m.direct?"TCP 使用三次成功连接的算术平均，失败单独计入丢包。":"各网站去掉最高和最低一次后，平均三个网站的均值。"}`;box.append(summary);$("detailDialog").showModal();}
function rules(values){if(ruleMode===mode)return;ruleMode=mode;const form=$("rulesForm");form.replaceChildren();const fields=mode==="tcp_tls"?tcpFields:proxyFields;for(const [key,title,min,max,step] of fields){const wrapper=document.createElement("label");wrapper.className="field";const text=document.createElement("span");text.textContent=title;const toggle=["tls_enabled","adaptive_concurrency","quick_finish"].includes(key),select=toggle||key==="download_bytes";const input=document.createElement(select?"select":"input");if(select){const options=toggle?[[0,"关闭"],[1,"开启"]]:[.5,1,2,4,8].map(n=>[n,`${n} MiB`]);for(const [value,label] of options){const option=document.createElement("option");option.value=value;option.textContent=label;input.append(option);}}else{input.type="number";input.min=min;input.max=max;input.step=step;if(min===max)input.readOnly=true;}input.required=true;input.name=key;input.value=key==="download_bytes"?values[key]/1048576:key==="minimum_completion_ratio"?values[key]*100:values[key];const help=document.createElement("small");help.className="field-help";help.id=`ruleHelp-${key}`;help.textContent=helps[key]||"严格按保存值执行。";input.setAttribute("aria-describedby",help.id);wrapper.append(text,input,help);form.append(wrapper);}}
function workflow(rows=[]){const labels={pending:"等待前一步",running:"进行中",completed:"已完成",waiting:"等待补测／推送",paused:"已暂停／保存",failed:"失败，断点保留"};let done=0,current="等待开始";for(const row of rows){const step=document.querySelector(`[data-step="${row.id}"]`);if(!step)continue;const status=Object.hasOwn(labels,row.status)?row.status:"pending";step.className=`flow-step ${status}${step.classList.contains("motion-offscreen")?" motion-offscreen":""}`;step.querySelector(".flow-state").textContent=labels[status];step.querySelector("small").textContent=row.detail||"";if(status==="completed")done++;if(["running","waiting","paused","failed"].includes(status))current=`${row.title}：${labels[status]}`;}$("flowProgress").value=done;$("flowStatus").textContent=`${done===5?"本轮已完成":current}，已完成 ${done} / 5 步`;}
async function logs(){const expected=mode,v=await post("log-events");if(expected!==mode)return;const signature=JSON.stringify(v.rows);if(signature===lastLog)return;lastLog=signature;const fragment=document.createDocumentFragment();for(const row of v.rows){const line=document.createElement("div");line.className=`event-line ${row.level}`;const time=document.createElement("time");time.textContent=new Date(row.time).toLocaleTimeString("zh-CN",{timeZone:"Asia/Shanghai",hour12:false});const message=document.createElement("span");message.textContent=row.message;line.append(time,message);fragment.append(line);}if(!v.rows.length){const line=document.createElement("p");line.textContent="等待本方式的本地事件…";fragment.append(line);}$("eventLog").replaceChildren(fragment);if($("followLog").checked)$("eventLog").scrollTop=$("eventLog").scrollHeight;}
async function poll(){clearTimeout(pollTimer);const ticket=++pollTicket;try{const query=booted?`?measurement_mode=${mode}`:"",r=await fetch(`/api/proxybench/state${query}`),v=await r.json();if(!r.ok)throw Error(v.error||"读取状态失败");if(ticket!==pollTicket)return;if(!booted){mode=v.measurement_mode||"proxy";booted=true;}const live=v.live||{},cloud=v.cloud||{},direct=mode==="tcp_tls",limits={general:v.rules.publish_count,japan:v.rules.jp_publish_count};for(const button of document.querySelectorAll("[data-mode]")){button.classList.toggle("selected",button.dataset.mode===mode);button.classList.toggle("secondary",button.dataset.mode!==mode);button.setAttribute("aria-pressed",String(button.dataset.mode===mode));}
 timing={elapsed_seconds:0,software_seconds:0,active:false,...v.timing};timingAnchor=performance.now();renderTimer();
 $("modeDescription").textContent=direct?"连续三次 TCP、可设置的 TLS 检测与直连下载；不调用本软件代理内核。":"通过规则代理访问谷歌、Cloudflare、GitHub，验证响应与小样本下载。";$("selectionStep").textContent=direct?"TCP／TLS 本地实测":"本地代理三网站实测";$("methodBadge").textContent=direct?"TCP／TLS 直连":"代理三网站";$("ruleModeTitle").textContent=modes[mode];$("proxySettings").hidden=direct;
 $("targetSummary").textContent=`常规 ${limits.general}＋日本 ${limits.japan}`;$("qualitySummary").textContent=`发布目标 ${limits.general}＋${limits.japan}；日本不占常规名额`;
 const stage=v.running&&!v.local_running&&cloud.stage?cloud.stage:live.stage;$("stage").textContent=label(stage);$("status").textContent=label(v.running?cloud.status||live.status:live.status||"Ready");$("counts").textContent=`${live.candidate_total||0} / ${live.tested_count||0}`;$("qualified").textContent=`${live.qualified_count||0} / ${Math.max(0,(live.tested_count||0)-(live.qualified_count||0))}`;$("batch").textContent=`第 ${live.batch_current||0}/${live.batch_total||0} 批；已初筛 ${live.entry_screened_count||0} 个`;
 $("core").textContent=direct?"TCP／TLS 直连":live.mihomo?.version||"等待内核准备";$("coreDetail").textContent=direct?"无需代理配置，使用本机网络路由":`规则模式，已加载 ${live.mihomo?.loaded_proxies||0} 个节点`;
 $("activeTask").textContent=v.active_mode?`正在运行：${modes[v.active_mode]}`:"当前没有运行任务";for(const button of document.querySelectorAll('[data-action="start"],[data-action="continue-fetch"]'))button.disabled=!!v.global_running;
 $("profileState").textContent=direct?"TCP／TLS 方式直接连接 IP；已有系统路由保持原状。":v.profile?.configured?"协议配置已就绪；每次运行检测本机配置和内核更新。":"尚无代理协议配置，可读取本机节点或先使用免代理方式。";
 for(const heading of document.querySelectorAll(".response-heading")){heading.textContent=direct?"TCP 延迟（毫秒）":"三网延迟（毫秒）";heading.title=direct?"连续三次 TCP 成功连接的平均值":"通过候选代理访问指定网站的延迟";}
 const a=v.modes?.proxy?.cloud||{},b=v.modes?.tcp_tls?.cloud||{};$("cloudPublishedCount").textContent=v.modes?`代理 ${a.total||0} 个（日本追加 ${a.japan||0}）；TCP／TLS ${b.total||0} 个（日本追加 ${b.japan||0}）`:`云端共 ${v.cloud_published?.total||0} 个 IP`;
 const h=v.published||{};$("publishState").textContent=h.published?`本方式本机结果：常规 ${h.general_final_count}＋日本 ${h.jp_final_count}，共 ${h.unique_final_count} 个；${cloud.status==="Completed"?"云端推送已确认":"等待云端确认"}。`:`本方式目标：常规 ${limits.general}＋日本 ${limits.japan}；停止保存后可手动推送实际合格数量。`;$("actions").href=v.actions_url;
 $("liveSelectionInfo").textContent=`${label(live.stage)}；通过 ${live.qualified_count||0} 个，每页 300 个`;
 $("competitionState").textContent=["general_retest","jp_retest"].includes(live.phase)?"正在竞赛复测，新旧 IP 均执行保存的规则。":"竞赛结果保留在独立窗口，不会与日常测试进度混合。";
 workflow(v.workflow);$("targetSummary").textContent=`常规 ${limits.general}＋日本 ${limits.japan}`;rules(v.rules);await Promise.all([refreshResults(),refreshCompetition(),logs()]);if($("candidateDetails").open)await refreshCandidates();else $("listTotal").textContent=`${(live.candidate_total||0).toLocaleString("zh-CN")} 个 IP`;
 if(cloud.status==="Failed")feedback(`${cloud.stage||"任务未完成"}。结果、断点和日志已保存在本机。`);else if(cloud.monitor_warning)feedback(cloud.monitor_warning);else if($("feedback").textContent==="正在读取本机状态…")feedback("选择顶部测速方式，设置发布数量，再开始优选。停止并保存只保存进度，推送请点击手动推送。");
 }catch(error){feedback(error.message||"本地服务暂时不可用");}finally{if(ticket===pollTicket)pollTimer=setTimeout(poll,2000);}}
for(const button of document.querySelectorAll("[data-mode]"))button.addEventListener("click",async()=>{try{await post("choose-mode",{mode:button.dataset.mode});mode=button.dataset.mode;booted=true;ruleMode=null;resultPage=candidatePage=competitionPage=1;signatures.clear();lastLog="";feedback(`已切换到${modes[mode]}，规则和断点分别保存。`);await poll();}catch(error){feedback(error.message);}});
for(const button of document.querySelectorAll("[data-action]"))button.addEventListener("click",async()=>{button.disabled=true;try{const v=await post(button.dataset.action);feedback(v.message||(button.dataset.action==="stop"?"已请求停止并保存结果与断点；需要发布时点击手动推送。":"操作已提交，请查看流程和实时日志。"));await poll();}catch(error){feedback(error.message);}finally{button.disabled=false;}});
for(const button of document.querySelectorAll("[data-results]"))button.addEventListener("click",async()=>{resultKind=button.dataset.results;resultPage=1;for(const other of document.querySelectorAll("[data-results]")){other.classList.toggle("selected",other===button);other.classList.toggle("secondary",other!==button);other.setAttribute("aria-pressed",String(other===button));}await refreshResults().catch(e=>feedback(e.message));});
for(const [prefix,change,refresh] of [["result",n=>resultPage=Math.max(1,resultPage+n),refreshResults],["competition",n=>competitionPage=Math.max(1,competitionPage+n),refreshCompetition],["cloud",n=>cloudPage=Math.max(1,cloudPage+n),refreshCloud],["candidate",n=>candidatePage=Math.max(1,candidatePage+n),refreshCandidates]]){const p=prefix==="candidate"?"previousPage":`${prefix}Previous`,n=prefix==="candidate"?"nextPage":`${prefix}Next`;$(p).addEventListener("click",()=>{change(-1);refresh().catch(e=>feedback(e.message));});$(n).addEventListener("click",()=>{change(1);refresh().catch(e=>feedback(e.message));});}
$("resultPageForm").addEventListener("submit",e=>{e.preventDefault();resultPage=Number($("resultPageNumber").value);refreshResults().catch(e=>feedback(e.message));});$("pageForm").addEventListener("submit",e=>{e.preventDefault();candidatePage=Number($("pageNumber").value);refreshCandidates().catch(e=>feedback(e.message));});$("candidateDetails").addEventListener("toggle",()=>{if($("candidateDetails").open)refreshCandidates().catch(e=>feedback(e.message));});
$("rulesForm").addEventListener("submit",async e=>{e.preventDefault();const values={},fields=mode==="tcp_tls"?tcpFields:proxyFields,data=new FormData(e.target);for(const [key] of fields)values[key]=Number(data.get(key));values.download_bytes*=1048576;values.minimum_completion_ratio/=100;try{const v=await post("rules",values);$("ruleFeedback").textContent=v.effective;await poll();}catch(error){$("ruleFeedback").textContent=error.message;}});
$("refreshCloud").addEventListener("click",async()=>{try{await post("refresh-cloud-results");await refreshCloud();}catch(error){feedback(error.message);}});$("closeDetail").addEventListener("click",()=>$("detailDialog").close());
$("autoImport").addEventListener("click",async()=>{try{await post("import-existing",{auto:true});feedback("已读取本机代理配置。参数仅保存在本机。");}catch(e){feedback(e.message);}});$("importProfile").addEventListener("click",async()=>{try{await post("import",{text:$("profileText").value});$("profileText").value="";feedback("代理配置已保存到本机。");}catch(e){feedback(e.message);}});
refreshCloud().catch(()=>{});setInterval(()=>refreshCloud().catch(()=>{}),5000);
const browserClient=crypto.randomUUID();const presence=closed=>fetch("/api/browser-presence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({client:browserClient,closed})}).catch(()=>{});presence(false);setInterval(()=>presence(false),15000);window.addEventListener("pagehide",()=>navigator.sendBeacon("/api/browser-presence",JSON.stringify({client:browserClient,closed:true})));poll();
(()=>{const layer=$("ambientParticles"),colors=["cyan","green","violet"];for(let i=0;i<30;i++){const p=document.createElement("i");p.className=`ambient-particle ${colors[i%3]}`;for(const [name,value] of Object.entries({x:`${(i*37+11)%100}%`,drift:`${(i*29)%31-15}vw`,size:`${2+i%4}px`,duration:`${14+i%8*2}s`,delay:`${-i%12*1.7}s`}))p.style.setProperty(`--${name}`,value);layer.append(p);}const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle("motion-offscreen",!e.isIntersecting)));for(const card of document.querySelectorAll(".flow-step,.result-tab")){const glow=document.createElement("span");glow.className="card-atmosphere";glow.setAttribute("aria-hidden","true");for(let i=0;i<32;i++){const p=document.createElement("i");for(const [name,value] of Object.entries({px:`${7+i*31%86}%`,pd:`${2.8+i%4*.4}s`,pl:`${-i*.31}s`,sway:`${i%2?24:-24}px`}))p.style.setProperty(`--${name}`,value);glow.append(p);}card.append(glow);observer.observe(card);}const visibility=()=>document.body.classList.toggle("page-hidden",document.hidden);document.addEventListener("visibilitychange",visibility);visibility();document.addEventListener("pointerdown",event=>{const button=event.target.closest(".button");if(!button||button.disabled)return;const rect=button.getBoundingClientRect(),ripple=document.createElement("span");ripple.className="ripple-ink";ripple.style.left=`${event.clientX-rect.left}px`;ripple.style.top=`${event.clientY-rect.top}px`;button.append(ripple);ripple.addEventListener("animationend",()=>ripple.remove(),{once:true});});})();
